# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pixel-city' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.4'

  # Pods for pixel-city

  target 'pixel-cityTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'pixel-cityUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
